enum ReduxActions {
  ASYNC_GET_DASHBOARD = '@ACIONS/ASYNC_GET_DASHBOARD',
  SET_DASHBOARD = '@ACIONS/SET_DASHBOARD',
  ASYNC_GET_STATEMENT_TYPES = '@ACIONS/ASYNC_GET_STATEMENT_TYPES',
  SET_STATEMENT_TYPES = '@ACIONS/SET_STATEMENT_TYPES',
  SET_DASHBOARD_LOADING = '@ACIONS/SET_DASHBOARD_LOADING',
  ASYNC_GET_MOUNTH_STATEMENTS = '@ACIONS/ASYNC_GET_MOUNTH_STATEMENTS',
  SET_MOUNTH_STATEMENTS = '@ACIONS/SET_MOUNTH_STATEMENTS',
  SET_MOUNTH_STATEMENTS_BALANCE = '@ACIONS/SET_MOUNTH_STATEMENTS_BALANCE',
  SET_MOUNTH_STATEMENTS_IS_LOADING = '@ACIONS/SET_MOUNTH_STATEMENTS_IS_LOADING',
  SET_STATEMENTS_IS_SENDING = '@ACIONS/SET_STATEMENTS_IS_SENDING',
  ASYNC_CREATE_STATEMENTS = '@ACIONS/ASYNC_CREATE_STATEMENTS',
  ASYNC_UPDATE_STATEMENTS = '@ACIONS/ASYNC_UPDATE_STATEMENTS',
  ASYNC_DELETE_STATEMENTS = '@ACIONS/ASYNC_DELETE_STATEMENTS',
  APPEND_STATEMENT_MOUNTH_ITEM = '@ACIONS/APPEND_STATEMENT_MOUNTH_ITEM',
}

export default ReduxActions;
