enum Routes {
  DASHBOARD = 'DASHBOARD',
  STATEMENTS = 'STATEMENTS',
  COPY_STATEMENTS = 'COPY_STATEMENTS',
  CREATE_EDIT_STATEMENTS = 'CREATE_EDIT_STATEMENTS',
  UPDATE_CARDS = 'UPDATE_CARDS',
}

export default Routes;
